### PR TITLE
Fix errors in test buffer_wrapper.pass

### PR DESCRIPTION
**Pull request by SergeyKopienko**
In this PR we fix compile error from the issue https://github.com/oneapi-src/oneDPL/issues/788 :
```
test/general/buffer_wrapper.pass.cpp:37:26: error: no matching conversion for functional-style cast from 'sycl::buffer<unsigned int, dim, aligned_allocator<unsigned int>>' to 'sycl::host_accessor<const unsigned int, 1, sycl::access_mode::read>'
        T* actual_data = sycl::host_accessor<T, 1, sycl::access_mode::read>(buf).get_pointer();
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This error were introduced in https://github.com/oneapi-src/oneDPL/pull/281

### CODE REVIEW

File: test/general/buffer_wrapper.pass.cpp [hunk 1]
```diff
@@ -48,7 +50,8 @@ main()
     std::size_t size = 1000;
     sycl::buffer<std::uint32_t> buf{size};
     test_buffer_wrapper test{};
-    auto data_ptr = sycl::host_accessor<std::uint32_t, 1, sycl::access_mode::read>(buf).get_pointer();
+    sycl::host_accessor buf_accessor(buf, sycl::read_only);
```
Comment (SergeyKopienko) [inline test/general/buffer_wrapper.pass.cpp:53]: In this line we use constructor as described at https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_interface_for_buffer_host_accessors :
```
  /* Available only when: (Dimensions > 0) */
  template <typename AllocatorT, typename TagT>
  host_accessor(buffer<DataT, Dimensions, AllocatorT>& bufferRef, TagT tag,
                const property_list& propList = {});
```

In the SYCL source code from DPCPP compiler it constructor from the file: https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/accessor.hpp, line 3019 :
```
  template <typename T = DataT, int Dims = Dimensions, typename AllocatorT,
            typename = detail::enable_if_t<IsSameAsBuffer<T, Dims>::value>>
  host_accessor(
      buffer<T, Dims, AllocatorT> &BufferRef, mode_tag_t<AccessMode>,
      const property_list &PropertyList = {},
      const detail::code_location CodeLoc = detail::code_location::current())
      : host_accessor(BufferRef, PropertyList, CodeLoc) {}
```

File: test/general/buffer_wrapper.pass.cpp [hunk 2]
```diff
@@ -34,7 +34,9 @@ struct test_buffer_wrapper
         EXPECT_TRUE(end - begin == size, "wrong effect of iterator's operator - iterator");
 
         auto buf = begin.get_buffer();
-        T* actual_data = sycl::host_accessor<T, 1, sycl::access_mode::read>(buf).get_pointer();
```
Comment (MikeDvorskiy) [inline test/general/buffer_wrapper.pass.cpp:37]: 1) By following up to the issue #788 where we have  got `'no matching conversion for functional-style cast from 'sycl::buffer<unsigned int, dim, aligned_allocator<unsigned int>>' to 'sycl::host_accessor<const unsigned int, 1, sycl::access_mode::read>'`
It tells that we have a buffer parametrized by `unsigned int` and `sycl::host_accessor` parametrized  by `const unsigned int`. 
2) The proposed changes probably doesn't resolve the issue because the SYCL spec tells " using value_type = // const DataT for read-only accessors, DataT otherwise" ,  so we have got the same error...

3) Furthermore, looking into the SYCL spec I cannot see such constructor with a buffer and access mode, how it is proposed in the changes.

**Review by MikeDvorskiy — CHANGES_REQUESTED** [review]
It looks the problem requires the further investigation....

File: test/general/buffer_wrapper.pass.cpp (hunk 2 above)
Comment (SergeyKopienko) [reply test/general/buffer_wrapper.pass.cpp:37]: About (3) - please see my comments at https://github.com/oneapi-src/oneDPL/pull/793#discussion_r1104332954
