### ISSUE TITLE
oneDPL + GCC 9 Very Sensitive to Include Order

### ISSUE THREAD

**Issue by krasznaa** [oneapi-src/oneDPL#1061]
This may be a well known issue, but it certainly made me lose a few hours of my life yesterday... :frowning:

The following simple source file does not compile on Ubuntu 20.04 (which comes with GCC 9).

```c++
#include <vector>
#include <oneapi/dpl/execution>

int main() {

   return 0;
}
```

It fails like:

```
[bash][atspot01]:dpl > icpx -fsycl ./dpltest.cpp 
In file included from ./dpltest.cpp:4:
In file included from /software/intel/oneapi-2023.2.0/dpl/2022.2.0/linux/include/oneapi/dpl/execution:23:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/execution:32:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/pstl/glue_execution_defs.h:52:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/pstl/algorithm_impl.h:25:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/pstl/parallel_backend.h:14:
/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/pstl/parallel_backend_tbb.h:70:10: error: no member named 'task' in namespace 'tbb'
    tbb::task::self().group()->cancel_group_execution();
    ~~~~~^
/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/pstl/parallel_backend_tbb.h:409:34: error: expected class name
class __merge_task : public tbb::task
                                 ^
/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/pstl/parallel_backend_tbb.h:411:23: error: no type named 'task' in namespace 'tbb'
    /*override*/ tbb::task*
                 ~~~~~^
...
```

If I reverse the include order however, the compilation succeeds. It took me quite a while to understand why this even happens. But basically, the hacks used in https://github.com/oneapi-src/oneDPL/blob/main/include/oneapi/dpl/internal/common_config.h only work if **no** C\+\+ standard library header was included yet. :frowning:

I understand that GCC 9 is problematic. :thinking: But would there really not be a way of handling the issue with GCC 9 + modern TBB in a way that would not be quite so fragile? :thinking:

Pinging @ivorobts.

**Comment by igorvorobtsov** [comment]
Hi @krasznaa. This is a known issue and it is documented in [Intel® oneAPI DPC++ Library Developer Guide](https://www.intel.com/content/www/us/en/docs/onedpl/developer-guide/2022-0/intel-oneapi-dpc-library-introduction.html):
"The use of oneDPL together with the GNU C++ standard library (libstdc++) version 9 or 10 may lead to compilation errors (caused by oneTBB API changes). Using libstdc++ version 9 requires TBB version 2020 for the header file. This may result in compilation errors when using C++17 or C++20 and TBB is not found in the environment, even if its use in oneDPL is switched off. To overcome these issues, include oneDPL header files before the standard C++ header files, or disable parallel algorithms support in the standard library. For more information, please see [Intel® oneAPI Threading Building Blocks (oneTBB) Release Notes](https://software.intel.com/content/www/us/en/develop/articles/intel-oneapi-threading-building-blocks-release-notes.html)."

**Comment by krasznaa** [comment]
This is definitely not the hill that I want to die on, but... Is there really no better way of disabling `libstdc++`'s TBB usage in these cases? The problem is that `c++config.h` freezes the values of a number of internal (`__` prefixed) variables in place, so oneDPL's effort to try to turn off TBB usage in `libstdc++` fails.

But as long as the oneDPL code already explicitly deals with GCC 9 and 10 in its source code, it might as well forcefully overwrite these internal variables of the standard library to make sure that it would not use TBB from oneAPI. 🤔

**Comment by igorvorobtsov** [comment]
It is a problem caused by gcc side, so, this was corrected and all works fine with latest gcc versions. To deal with that with gcc 9 the simplest way is to include oneDPL header first.

**Comment by akukanov** [comment]
In #1250 we are trying to advance the workaround for the issue, by checking and undefining libstdc++ internal macros that control their use of TBB. The PR has been merged and will be released in the next library update.

There is still a limitation that the workaround (i.e. any oneDPL header) needs to be included before the standard <execution> header code where the macros really take effect. Other standard headers however can go before or after oneDPL. I think it's the best we can do for a problem in the code outside of our direct control.
