### PR TITLE
Fix error in iterator comparison

### PR DESCRIPTION
**Pull request by SergeyKopienko**
In this PR we fix an error in the comparison of input and output iterators which was introduced in https://github.com/oneapi-src/oneDPL/pull/761 :
in this comparison we receive compile error in DPC++ compiler (win) ```Error GE509BDA3 invalid operands to binary expression```

### CODE REVIEW

File: include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h [hunk 1]
```diff
@@ -155,6 +155,28 @@ __pattern_transform_scan_base_impl(_ExecutionPolicy&& __exec, _Iterator1 __first
...
+template <typename Iterator>
+bool
+__is_equal_iterators_impl(Iterator it1, Iterator it2)
+{
+    return it1 == it2;
+}
+
+template <typename Iterator1, typename Iterator2>
+bool
+__is_equal_iterators_impl(Iterator1 it1, Iterator2 it2)
```
Comment (MikeDvorskiy) [inline include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h:167]: I think it is a redefinition of `__is_equal_iterators_impl` in case of Iterator1 and Iterator2 are the same type..
Please use SFINAE approach, like this
https://godbolt.org/z/rGfz7j8nh

File: include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h [hunk 2]
```diff
@@ -155,6 +155,28 @@ __pattern_transform_scan_base_impl(_ExecutionPolicy&& __exec, _Iterator1 __first
...
+{
+    static_assert("Unable to compare the iterators of different types");
```
Comment (MikeDvorskiy) [inline include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h:169]: Should be another text, like this:
"In-place exclusive scan works correctly only if an input and an output iterators are the same type."

**Review by MikeDvorskiy — CHANGES_REQUESTED** [review]

File: include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h (hunk 2 above)
Comment (SergeyKopienko) [reply include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h]: Fixed

File: include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h (hunk 1 above)
Comment (SergeyKopienko) [reply include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h]: Fixed

File: include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h [hunk 3]
```diff
@@ -155,6 +155,21 @@ __pattern_transform_scan_base_impl(_ExecutionPolicy&& __exec, _Iterator1 __first
...
+__is_equal_iterators(Iterator1 it1, Iterator2 it2)
+{
+    return it1 == it2;
+}
+
+template <typename Iterator1, typename Iterator2, std::enable_if_t<!std::is_same_v<Iterator1, Iterator2>, int> = 0>
+constexpr bool
+__is_equal_iterators(Iterator1 it1, Iterator2 it2)
+{
+    static_assert("In-place exclusive scan works correctly only if an input and an output iterators are the same type.");
```
Comment (MikeDvorskiy) [inline include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h:169]: And should not be any assert here - just a comment.
Otherwise it "kills" the regular implementation  - "else" code branch (191)

Comment (SergeyKopienko) [reply include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h]: FYI: in our tests, there are no cases when it's happened now in our tests.
If we will have a simple comment, depending on iterator types we have correct/incorrect working code without compile errors.
But up to you.

Comment (SergeyKopienko) [reply include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h]: Fixed

File: include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h [hunk 4]
```diff
@@ -155,6 +155,21 @@ __pattern_transform_scan_base_impl(_ExecutionPolicy&& __exec, _Iterator1 __first
         .wait();
 }
 
+template <typename Iterator1, typename Iterator2, std::enable_if_t<std::is_same_v<Iterator1, Iterator2>, int> = 0>
```
Comment (MikeDvorskiy) [inline include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h]: I would like to notice that for example a case `const Iterator1 `and `Iterator2` should work as well here.
Because it is a typical case when input iterator is const, output is non-const (of course).

File: include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h (hunk 3 above)
Comment (MikeDvorskiy) [reply include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h]: > in our tests

"Unfortunately", a user runs not only our tests)...

Comment (SergeyKopienko) [reply include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h]: Yes, sure, and in this case better to have some info is our algorithm works correctly or not.
How are you going to give this use to oneDPL users? Simple by comment?

Comment (MikeDvorskiy) [reply include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h]: > we have correct/incorrect working code without compile errors.

Unfortunately, there is no way to check it whether compile time or run time in a general case.

File: include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h [hunk 5]
```diff
@@ -167,7 +183,7 @@ __pattern_transform_scan_base(_ExecutionPolicy&& __exec, _Iterator1 __first, _It
     const auto __n = __last - __first;
 
     // This is a temporary workaround for an in-place exclusive scan while the SYCL backend scan pattern is not fixed.
-    const bool bInplaceExclusiveScan = __n > 1 && !_Inclusive{} && __first == __result;
+    const bool bInplaceExclusiveScan = __n > 1 && !_Inclusive{} && __is_equal_iterators(__first, __result);
```
Comment (akukanov) [inline include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h:186]: We do not use the Hungarian notation, and we (sort of have to) use uglification. This variable is better named `__is_scan_inplace_exclusive`

Also please add all needed underscores to the `__is_equal_iterators` helper.

File: include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h (hunk 4 above)
Comment (SergeyKopienko) [reply include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h]: Already fixed.

File: include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h (hunk 5 above)
Comment (SergeyKopienko) [reply include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h]: Fixed.

File: include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h (hunk 3 above)
Comment (SergeyKopienko) [reply include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h]: I believe we may check that ```std::address()``` is applicable for current iterator type and in this case use it too before ```return false``` in ```__is_equal_iterators``` function.

File: include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h [hunk 6]
```diff
@@ -155,6 +155,22 @@ __pattern_transform_scan_base_impl(_ExecutionPolicy&& __exec, _Iterator1 __first
         .wait();
 }
 
+template <typename _Iterator1, typename _Iterator2>
+constexpr bool
+__is_equal_iterators(_Iterator1 it1, _Iterator2 it2)
```
Comment (MikeDvorskiy) [inline include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h:160]: As far as we have a plural form  - "iterators" we have to use the other form of "to be" verb  or don't use "to be" at all. So, my suggestion
`__are_equal_iterators` or `__check_equal_iterators`

Comment (SergeyKopienko) [reply include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h:160]: OK, let's use your variant ``` __check_equal_iterators```

Comment (SergeyKopienko) [reply include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h]: Fixed.

File: include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h [hunk 7]
```diff
@@ -155,6 +155,22 @@ __pattern_transform_scan_base_impl(_ExecutionPolicy&& __exec, _Iterator1 __first
...
+{
+    using _Decay_Iterator1 = std::decay_t<_Iterator1>;
+    using _Decay_Iterator2 = std::decay_t<_Iterator2>;
+
+    if constexpr (std::is_same_v<_Decay_Iterator1, _Decay_Iterator2>)
+    {
+        return it1 == it2;
+    }
+
+    // In-place exclusive scan works correctly only if an input and an output iterators are the same type.
```
Comment (MikeDvorskiy) [inline include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h:170]: I think the comment describes the situation non quite right. 
Lets add the following text:
"Otherwise, there is no way to check an in-place case and a workaround below is not applied."

Comment (SergeyKopienko) [reply include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h]: Fixed,

**Review by MikeDvorskiy — APPROVED** [review]

File: include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h [hunk 8]
```diff
@@ -155,6 +155,23 @@ __pattern_transform_scan_base_impl(_ExecutionPolicy&& __exec, _Iterator1 __first
         .wait();
 }
 
+template <typename _Iterator1, typename _Iterator2>
+constexpr bool
+__check_equal_iterators(_Iterator1 it1, _Iterator2 it2)
```
Comment (akukanov) [inline include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h:160]: `it1` and `it2` also need underscores.

Comment (SergeyKopienko) [reply include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h]: Fixed

**Review by akukanov — APPROVED** [review]
