### PR TITLE
[Tests] Fix xpu tests (regression since #992)

### PR DESCRIPTION
**Pull request by dmitriy-sobolev**
It fixes "error: no member named 'done' in namespace 'TestUtils'". The error is introduced by #992.

### CODE REVIEW

**Review by mmichel11 — APPROVED** [review]
LGTM. I have also verified that the three unchanged files from PR #992 already include utils.h

**Review by SergeyKopienko — APPROVED** [review]
LGTM
