### PR TITLE
Fix a compilation error in async algorithms introduced by #811

### PR DESCRIPTION
**Pull request by akukanov**
My bad, forgot to change the use of `__is_convertible_to_event` after changing its definition from `bool_constant` to `bool`.

### CODE REVIEW

**Review by SergeyKopienko — APPROVED** [review]
LGTM, compile error fixed.
